const products = [
  {name:'Créatine Monohydrate',brand:'CRÉATINE',category:'PERFORMANCE',image:'product-01.png',price:'À partir de 300 DH',note:'250 g : 300 DH au lieu de 350 DH · 500 g : 450 DH au lieu de 500 DH',intro:'Un soutien simple pour les efforts courts, répétés et intenses. Disponible en formats 250 g et 500 g.',tags:['Force','Puissance','250 g / 500 g'],facts:[['Force explosive','Aide à améliorer la performance lors des séries courtes et intenses.'],['Répétition des efforts','Utile pour mieux maintenir la qualité des efforts répétés à l’entraînement.'],['Progression','Associée à un entraînement régulier, elle soutient la progression en force et en masse musculaire.']],use:'Suivez la portion indiquée sur le produit, généralement mélangée avec de l’eau. La régularité compte davantage que l’heure exacte.',timing:'Chaque jour, à un moment facile à maintenir. Les jours d’entraînement comme les jours de repos.',caution:'Une légère prise de poids liée à l’eau stockée dans le muscle est normale. Hydratez-vous correctement.'},
  {name:'Super Mass Gainer',brand:'DYMATIZE',category:'PRISE DE MASSE',image:'product-02.png',price:'610 DH',old:'650',intro:'Une formule riche en calories pour les sportifs qui ont du mal à atteindre leur apport énergétique quotidien.',tags:['Calories','Masse','Glucides + protéines'],facts:[['Apport calorique','Augmente facilement les calories quotidiennes nécessaires à une prise de poids.'],['Construction musculaire','Apporte des protéines qui contribuent au maintien et au développement musculaire.'],['Récupération énergétique','Les glucides aident à reconstituer les réserves d’énergie après un effort exigeant.']],use:'Commencez par une demi-portion pour évaluer votre tolérance, puis adaptez selon vos besoins caloriques et l’étiquette.',timing:'Entre les repas ou après l’entraînement. Il complète l’alimentation, sans remplacer les vrais repas.',caution:'Un surplus calorique trop important favorise aussi la prise de graisse. Ajustez la portion à votre objectif.'},
  {name:'Amino Energy Drink',brand:'OPTIMUM NUTRITION',category:'ÉNERGIE',image:'product-03.png',price:'25 DH',intro:'Une boisson pratique pour apporter un coup de boost et accompagner les journées ou séances actives.',tags:['Énergie','Prêt à boire','25 DH / unité'],facts:[['Énergie rapide','Pensée pour soutenir la vigilance et l’énergie avant ou pendant une activité.'],['Format pratique','Prête à boire, facile à emporter à la salle ou pendant une journée chargée.'],['Acides aminés','Apporte des acides aminés en complément de l’alimentation quotidienne.']],use:'Consommez une unité en respectant les indications de l’emballage.',timing:'Avant l’entraînement ou pendant la journée lorsque vous avez besoin de concentration.',caution:'Vérifiez la teneur en caféine. Évitez le soir et ne cumulez pas plusieurs sources stimulantes.'},
  {name:'Lean Mass Gainer',brand:'APPLIED NUTRITION',category:'PRISE DE MASSE',image:'product-04.png',price:'580 DH',old:'600',intro:'Un gainer conçu pour augmenter l’apport en protéines et en calories dans le cadre d’une prise de masse maîtrisée.',tags:['Masse','Protéines','Calories'],facts:[['Surplus calorique','Aide à atteindre un apport énergétique supérieur lorsque l’alimentation seule ne suffit pas.'],['Protéines','Contribue au maintien et au développement de la masse musculaire.'],['Praticité','Permet de préparer rapidement une collation calorique mesurable.']],use:'Mélangez la portion recommandée avec de l’eau ou du lait selon vos besoins caloriques.',timing:'Après la séance ou en collation entre deux repas.',caution:'Adaptez les portions à votre dépense énergétique et à votre alimentation globale.'},
  {name:'Creatine Monohydrate',brand:'APPLIED NUTRITION',category:'PERFORMANCE',image:'product-05.png',price:'520 DH',old:'550',intro:'De la créatine monohydrate pour soutenir la puissance et les efforts musculaires de haute intensité.',tags:['Puissance','Force','Usage quotidien'],facts:[['Performance intense','Soutient les performances physiques lors d’efforts successifs, courts et très intenses.'],['Force','Accompagne un programme visant la progression des charges.'],['Réserves musculaires','Augmente les réserves musculaires de créatine lorsqu’elle est prise régulièrement.']],use:'Prenez chaque jour la dose indiquée sur l’emballage, mélangée à la boisson de votre choix.',timing:'À tout moment de la journée. Choisissez surtout un horaire que vous pouvez respecter.',caution:'Buvez suffisamment d’eau. Demandez un avis médical en cas de problème rénal connu.'},
  {name:'ISO100 Hydrolyzed',brand:'DYMATIZE',category:'WHEY ISOLATE',image:'product-06.png',price:'980 DH',old:'1050',intro:'Une protéine isolate hydrolysée pensée pour une digestion rapide et un apport protéique de haute qualité.',tags:['Isolate','Hydrolysée','Récupération'],facts:[['Apport protéique','Aide à atteindre l’objectif quotidien en protéines nécessaire au maintien musculaire.'],['Récupération','Fournit des acides aminés utiles à la réparation musculaire après l’entraînement.'],['Digestion rapide','Le format hydrolysé est conçu pour être assimilé rapidement et facilement.']],use:'Mélangez une portion selon l’étiquette avec de l’eau ou du lait.',timing:'Après l’entraînement ou à tout moment où l’apport en protéines du repas est insuffisant.',caution:'Vérifiez les allergènes et la tolérance aux produits laitiers sur l’étiquette.'},
  {name:'Super Mass Gainer',brand:'DYMATIZE',category:'PRISE DE MASSE',image:'product-07.png',price:'950 DH',intro:'Un grand format calorique pour accompagner les phases de prise de masse et les besoins énergétiques élevés.',tags:['Grand format','Calories','Masse'],facts:[['Prise de poids','Facilite la création d’un surplus calorique quotidien.'],['Énergie','Apporte des glucides utiles pour soutenir un volume d’entraînement important.'],['Muscles','Les protéines contribuent à la croissance et au maintien musculaire.']],use:'Préparez la portion indiquée; commencez plus bas si une portion complète est difficile à digérer.',timing:'En collation ou après la séance, selon votre plan alimentaire.',caution:'Ce produit est très calorique. Calculez vos besoins pour limiter une prise de graisse excessive.'},
  {name:'Energy & Hydration',brand:'HYDRATATION',category:'HYDRATATION',image:'product-08.png',price:'400 DH',note:'2 boîtes : 780 DH',intro:'Une formule conçue pour soutenir l’hydratation et l’énergie pendant les séances, la chaleur ou les longues journées actives.',tags:['Hydratation','Électrolytes','Offre duo'],facts:[['Hydratation','Aide à compléter l’apport en liquides pendant l’activité physique.'],['Électrolytes','Soutient le remplacement des minéraux perdus par la transpiration.'],['Endurance','Une bonne hydratation aide à maintenir les performances au fil de la séance.']],use:'Diluez la portion indiquée dans le volume d’eau recommandé sur l’emballage.',timing:'Avant et pendant l’effort, particulièrement lorsqu’il fait chaud ou que la séance est longue.',caution:'Tenez compte du sodium, des sucres et des stimulants éventuels indiqués sur l’étiquette.'},
  {name:'Gold Standard Whey',brand:'OPTIMUM NUTRITION',category:'WHEY PROTEIN',image:'product-09.png',price:'1150 DH',old:'1200',intro:'Une whey polyvalente pour compléter facilement l’apport quotidien en protéines et soutenir la récupération.',tags:['Whey','Muscles','Récupération'],facts:[['Objectif protéines','Permet d’atteindre plus facilement votre quantité quotidienne de protéines.'],['Masse musculaire','Les protéines contribuent au développement et au maintien musculaire.'],['Collation pratique','Une solution rapide lorsque préparer une source de protéines complète n’est pas possible.']],use:'Mélangez la portion indiquée avec de l’eau ou du lait selon vos préférences.',timing:'Après la séance, au petit-déjeuner ou en collation selon vos besoins.',caution:'Un shaker complète une alimentation équilibrée; il ne remplace pas systématiquement un repas.'},
  {name:'ISO Whey Zero',brand:'BIOTECH USA',category:'WHEY ISOLATE',image:'product-10.png',price:'1100 DH',intro:'Une whey isolate concentrée en protéines, adaptée aux phases où l’on surveille particulièrement les apports.',tags:['Isolate','Protéines','Définition'],facts:[['Protéines concentrées','Apporte une forte proportion de protéines par portion selon la saveur choisie.'],['Récupération','Aide à fournir les acides aminés nécessaires après l’entraînement.'],['Gestion des apports','Une isolate contient généralement moins de sucres et de graisses qu’une whey classique; vérifiez l’étiquette.']],use:'Mélangez la dose recommandée avec de l’eau pour une boisson légère.',timing:'Après l’entraînement ou entre les repas pour compléter l’apport protéique.',caution:'Consultez les allergènes et les valeurs nutritionnelles exactes de votre saveur.'},
  {name:'Joyfuel',brand:'ENERGY DRINK',category:'ÉNERGIE',image:'product-11.png',price:'25 DH',intro:'Une boisson énergisante en format individuel pour accompagner les moments demandant vigilance et dynamisme.',tags:['Énergie','Unité','Prêt à boire'],facts:[['Coup de boost','Peut soutenir temporairement la vigilance lorsque la formule contient de la caféine.'],['Praticité','Format prêt à boire facile à emporter.'],['Avant l’effort','Peut convenir avant une séance si vous tolérez bien les stimulants.']],use:'Limitez-vous à la quantité recommandée sur la canette.',timing:'En journée ou avant l’effort, suffisamment tôt pour ne pas gêner le sommeil.',caution:'Contrôlez la caféine totale de la journée. Déconseillé aux enfants et aux personnes sensibles aux stimulants.'},
  {name:'Lean Mass Gainer',brand:'APPLIED NUTRITION',category:'PRISE DE MASSE',image:'product-12.png',price:'990 DH',old:'1050',intro:'Un grand format pour augmenter les calories et les protéines pendant une phase structurée de prise de masse.',tags:['Grand format','Masse','Protéines'],facts:[['Calories faciles','Simplifie l’ajout d’une collation calorique mesurée.'],['Développement musculaire','Les protéines soutiennent la croissance musculaire avec un entraînement adapté.'],['Récupération','Les glucides et protéines accompagnent la récupération après une séance exigeante.']],use:'Mélangez selon les instructions. Fractionnez la portion en deux prises si nécessaire.',timing:'Entre les repas ou après l’entraînement.',caution:'Surveillez l’évolution du poids chaque semaine pour ajuster la portion progressivement.'},
  {name:'Multivitamines',brand:'VITAMINES',category:'BIEN-ÊTRE',image:'product-13.png',price:'300 DH',intro:'Un complément quotidien destiné à compléter les apports en vitamines et minéraux lorsque l’alimentation présente des manques.',tags:['Vitamines','Minéraux','Quotidien'],facts:[['Complément alimentaire','Aide à couvrir certains micronutriments lorsque les apports alimentaires sont insuffisants.'],['Métabolisme énergétique','Plusieurs vitamines participent au fonctionnement normal du métabolisme énergétique.'],['Routine simple','Regroupe différents micronutriments dans une prise pratique.']],use:'Prenez uniquement la portion indiquée, de préférence avec un repas.',timing:'Avec le petit-déjeuner ou le déjeuner pour une meilleure tolérance digestive.',caution:'Ne cumulez pas plusieurs multivitamines. Plus n’est pas mieux, certaines vitamines s’accumulent dans l’organisme.'},
  {name:'Omega Balance',brand:'BIEN-ÊTRE',category:'OMÉGA',image:'product-14.png',price:'300 DH',intro:'Une source d’acides gras essentiels destinée à compléter une alimentation pauvre en poissons gras.',tags:['Acides gras','Équilibre','Avec repas'],facts:[['Apport en oméga','Complète l’alimentation en acides gras selon la composition exacte du produit.'],['Routine nutritionnelle','Pratique lorsque la consommation de poissons gras est faible.'],['Absorption','Les matières grasses du repas favorisent l’absorption des capsules huileuses.']],use:'Respectez la portion et la teneur en EPA/DHA précisées sur l’étiquette.',timing:'Pendant un repas contenant des matières grasses.',caution:'Demandez conseil à un professionnel si vous prenez un traitement anticoagulant.'},
  {name:'Opti-Men Multivitamines',brand:'OPTIMUM NUTRITION',category:'BIEN-ÊTRE',image:'product-15.png',price:'420 DH',old:'450',intro:'Un complexe de vitamines et minéraux conçu pour compléter la routine nutritionnelle des hommes actifs.',tags:['Vitamines','Minéraux','Hommes actifs'],facts:[['Micronutriments','Complète les vitamines et minéraux apportés par une alimentation variée.'],['Énergie normale','Plusieurs vitamines du groupe B contribuent à un métabolisme énergétique normal.'],['Usage pratique','Une formule combinée facile à intégrer à la routine quotidienne.']],use:'Suivez strictement la portion de l’étiquette et prenez-la avec de la nourriture.',timing:'Répartie avec les repas si l’étiquette le recommande.',caution:'Évitez de l’associer à un autre multivitamines afin de ne pas dépasser certains apports.'},
  {name:'Energy & Hydration',brand:'OPTIMUM NUTRITION',category:'HYDRATATION',image:'product-16.png',price:'400 DH',old:'450',intro:'Une préparation pour soutenir l’hydratation, l’énergie et la concentration autour des entraînements.',tags:['Hydratation','Énergie','Entraînement'],facts:[['Liquides','Encourage une consommation régulière d’eau pendant l’effort.'],['Minéraux','Peut aider à remplacer les électrolytes perdus avec la transpiration selon sa formule.'],['Concentration','Les ingrédients énergétiques éventuels peuvent soutenir la vigilance pendant la séance.']],use:'Diluez la portion recommandée dans la quantité d’eau indiquée.',timing:'Avant ou pendant l’entraînement.',caution:'Vérifiez la présence et la quantité de caféine avant de l’associer à un pré-workout ou un café.'},
  {name:'Pre-Workout Drink',brand:'PRE-WORKOUT',category:'ÉNERGIE',image:'product-17.png',price:'20 DH',intro:'Une boisson pré-entraînement individuelle conçue pour donner de l’énergie et du focus avant la séance.',tags:['Pré-workout','Focus','20 DH / unité'],facts:[['Énergie','Les stimulants éventuels peuvent réduire temporairement la sensation de fatigue.'],['Concentration','Pensée pour aider à entrer dans la séance avec davantage de focus.'],['Format rapide','Prête à boire et facile à doser grâce au format individuel.']],use:'Consommez au maximum la portion indiquée sur le contenant.',timing:'Environ 20 à 30 minutes avant l’entraînement, selon l’étiquette.',caution:'Ne mélangez pas avec d’autres stimulants et évitez une prise proche du coucher.'},
  {name:'R1 Whey Blend',brand:'RULE 1',category:'WHEY PROTEIN',image:'product-18.png',price:'850 DH',old:'890',intro:'Un mélange de protéines laitières polyvalent pour soutenir les besoins musculaires et la récupération quotidienne.',tags:['Whey blend','Protéines','Récupération'],facts:[['Apport quotidien','Aide à compléter les protéines consommées dans les repas.'],['Construction musculaire','Les protéines participent au développement musculaire avec un entraînement de résistance.'],['Polyvalence','Se consomme en shaker ou dans une recette selon vos préférences.']],use:'Mélangez une portion comme indiqué sur l’étiquette avec de l’eau ou du lait.',timing:'Après l’entraînement ou en collation dans la journée.',caution:'Adaptez le nombre de portions à vos besoins réels en protéines et à votre alimentation.'},
  {name:'Serious Mass',brand:'OPTIMUM NUTRITION',category:'PRISE DE MASSE',image:'product-19.png',price:'1050 DH',old:'1100',intro:'Un mass gainer très calorique destiné aux sportifs ayant des besoins élevés ou des difficultés à prendre du poids.',tags:['Haute calorie','Masse','Récupération'],facts:[['Surplus énergétique','Aide à apporter beaucoup de calories dans un format liquide.'],['Glucides','Contribue à reconstituer les réserves énergétiques après des entraînements volumineux.'],['Protéines','Soutient la croissance musculaire lorsque l’entraînement et l’alimentation sont adaptés.']],use:'Commencez avec une portion réduite, puis augmentez progressivement selon votre tolérance et vos besoins.',timing:'Après l’entraînement ou entre les repas, jamais au détriment d’une alimentation variée.',caution:'Très calorique: suivez votre poids et votre tour de taille pour ajuster la dose intelligemment.'}
];

products.push({
  name:'ISO100 Hydrolyzed 650 g',
  brand:'DYMATIZE',
  category:'WHEY ISOLATE',
  image:'product-06.png',
  price:'600 DH',
  old:'650',
  variants:['Chocolat Peanut Butter','Fraise','Fruity Pebbles','Double Chocolat'],
  intro:'Une protéine isolate hydrolysée en format 650 g, conçue pour une digestion rapide et un apport protéique de haute qualité.',
  tags:['650 g','4 saveurs','Isolate hydrolysée'],
  facts:[['Apport protéique','Aide à atteindre l’objectif quotidien en protéines nécessaire au maintien musculaire.'],['Récupération','Fournit des acides aminés utiles à la réparation musculaire après l’entraînement.'],['Digestion rapide','Le format hydrolysé est conçu pour être assimilé rapidement et facilement.']],
  use:'Mélangez une portion selon l’étiquette avec de l’eau ou du lait.',
  timing:'Après l’entraînement ou à tout moment où l’apport en protéines du repas est insuffisant.',
  caution:'Vérifiez les allergènes et la tolérance aux produits laitiers sur l’étiquette.'
});

const productVariantConfig = {
  2: {name:'Super Mass Gainer 2,7 kg', tags:['2,7 kg','Vanille','Chocolat'], variants:['Vanille','Chocolat']},
  6: {name:'ISO100 Hydrolyzed 1,3 kg', tags:['1,3 kg','Chocolat Peanut Butter','Vanille','Double Chocolat'], variants:['Chocolat Peanut Butter','Vanille','Double Chocolat']},
  7: {name:'Super Mass Gainer 5,44 kg', tags:['5,44 kg','Vanille','Chocolat'], variants:['Vanille','Chocolat']}
};

const id = Number(new URLSearchParams(window.location.search).get('id'));
const product = products[id - 1];
if (product && productVariantConfig[id]) Object.assign(product, productVariantConfig[id]);
if (!product) {
  document.querySelector('#product-detail').outerHTML = '<main class="not-found"><h1>PRODUIT INTROUVABLE</h1><a href="index.html#products">← Retour au catalogue</a></main>';
} else {
  document.title = `${product.name} | Moul Proteines`;
  document.querySelector('#detail-image').src = `assets/products/${product.image}`;
  document.querySelector('#detail-image').alt = product.name;
  document.querySelector('#detail-category').textContent = product.category;
  document.querySelector('#detail-brand').textContent = product.brand;
  document.querySelector('#detail-name').textContent = product.name;
  document.querySelector('#image-number').textContent = String(id).padStart(2, '0');
  document.querySelector('#detail-intro').textContent = product.intro;
  const priceMatch = product.price.match(/^(.*?)(\d+)\s*DH$/);
  document.querySelector('#detail-price').innerHTML = priceMatch ? `${priceMatch[1]}${priceMatch[2]} <small>DH</small>${product.old ? ` <del>${product.old} DH</del>` : ''}${product.note ? `<span class="price-note">${product.note}</span>` : ''}` : product.price;
  document.querySelector('#quick-facts').innerHTML = product.tags.map(tag => `<span>${tag}</span>`).join('');
  document.querySelector('#facts-grid').innerHTML = product.facts.map((fact, index) => `<article class="fact-card"><span>0${index + 1}</span><h3>${fact[0]}</h3><p>${fact[1]}</p></article>`).join('');
  document.querySelector('#detail-use').textContent = product.use;
  document.querySelector('#detail-timing').textContent = product.timing;
  document.querySelector('#detail-caution').textContent = product.caution;
  const variantContainer = document.querySelector('#detail-variant');
  if (product.variants) {
    const price = Number((product.price.match(/\d+/) || [0])[0]);
    const options = product.variants.map(variant => `<option value="${variant}" data-price="${price}">${variant}</option>`).join('');
    variantContainer.innerHTML = `<label>Choisir la saveur<select id="detail-variant-select">${options}</select></label>`;
  } else if (id === 1) {
    variantContainer.innerHTML = '<label>Choisir le format<select id="detail-variant-select"><option value="250 g" data-price="300">250 g — 300 DH au lieu de 350 DH</option><option value="500 g" data-price="450">500 g — 450 DH au lieu de 500 DH</option></select></label>';
  }
  const selectedProduct = () => {
    const select = document.querySelector('#detail-variant-select');
    if (!select) return {id, name: product.name, price: Number((product.price.match(/\d+/) || [0])[0])};
    const option = select.selectedOptions[0];
    return {id: `${id}-${option.value}`, name: `${product.name} ${option.value}`, price: Number(option.dataset.price)};
  };
  const updateOrderLink = () => {
    const selected = selectedProduct();
    document.querySelector('#detail-order').href = `https://wa.me/212774145588?text=${encodeURIComponent(`Bonjour, je souhaite commander : ${selected.name} (${selected.price} DH)`)}`;
  };
  document.querySelector('#detail-variant-select')?.addEventListener('change', updateOrderLink);
  updateOrderLink();
  document.querySelector('#detail-add-cart').addEventListener('click', () => {
    let cart = [];
    try { cart = JSON.parse(localStorage.getItem('mp-cart')) || []; } catch (error) { cart = []; }
    const selected = selectedProduct();
    const existing = cart.find(item => String(item.id) === String(selected.id));
    if (existing) existing.quantity += 1;
    else cart.push({...selected, image: `assets/products/${product.image}`, quantity: 1});
    try { localStorage.setItem('mp-cart', JSON.stringify(cart)); } catch (error) { /* Storage can be unavailable. */ }
    const toast = document.querySelector('#toast');
    toast.textContent = `${selected.name} ajouté au panier`;
    toast.classList.add('show');
    setTimeout(() => toast.classList.remove('show'), 1800);
  });
}
